import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { PoppinsFont } from '../common/style/font'
import './globals.css'
import { Providers } from '../common/utils/provider'
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={PoppinsFont.className}>
        <Providers>
          {children}
          <ToastContainer />
        </Providers>
      </body>
    </html>
  )
}
