import type { Metadata } from "next";
import { PoppinsFont } from "../common/style/font";
import "./globals.css";
import { Providers } from "../common/lib/provider";
import { Toaster } from "sonner";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={PoppinsFont.className}>
        <Providers>
          {children}
          <Toaster theme="light" position="top-right" richColors />
        </Providers>
      </body>
    </html>
  );
}
